language: smalltalk
sudo: false

os:
  - linux
  - osx

before_install:
  - |
    case $TRAVIS_OS_NAME in
    linux)
      sudo apt-add-repository --yes ppa:duggan/bats
      sudo apt-get update --quiet
      sudo apt-get install --yes bats bc
      ;;
    osx) brew install bats-core bc ;;
    esac

smalltalk:
  - Pharo-7.0
  - Pharo64-7.0
  - Pharo-6.1
  - Pharo64-6.1

script:
  - "$SMALLTALK_CI_HOME/run.sh"
  - bats test.bats
