language: smalltalk
sudo: true

os:
  - osx
  - linux

smalltalk:
  - Pharo64-alpha
  - Pharo64-stable
  - Pharo32-stable

matrix:
  fast_finish: true
  allow_failures:
    - smalltalk: Pharo64-alpha
      os: linux
