language: smalltalk
sudo: false

os:
  - linux
  - osx

before_install:
  - |
    case $TRAVIS_OS_NAME in
    linux)
      git clone --depth 1 --branch v1.1.0 https://github.com/bats-core/bats-core.git
      export PATH="$(pwd)/bats-core/bin:$PATH"
      ;;
    osx)
      brew install bats-core
      ;;
    esac

smalltalk:
  - Pharo-7.0
  - Pharo64-7.0
  - Pharo-6.1
  - Pharo64-6.1

script:
  - "$SMALLTALK_CI_HOME/run.sh"
  - bats tests
